# -*- coding: utf-8 -*-
"""EBAC - Calculadora.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_04_mbWDy-pkjAcg0zj4B8OiTS8Hi6cY

#Calculadora inteligente
Após o usuário informar qual operação deseja realizar, ele informa dois números e a calculadora retorna o resultado.
"""

#Mensagens
boas_vindas = 'Seja bem vindo à calculadora inteligente!'
opcoes = '''Informe a opção desejada:
1 - Adição
2 - Subtração
3 - Multiplicação
4 - Exponenciação
5 - Divisão
6 - Descobrir se um número é par ou ímpar
7 - Comparação de números
8 - Todas as opções acima
9 - Sair do programa

***Importante notar que a ordem que os números forem informados influenciará os resultados.
Aconselhável informar apenas números inteiros***'''
finalizacao = 'Foi ótimo ter você aqui. Até mais!'
interacao = '''Gostaria de retornar ao menu principal?
1 - Sim
2 - Não'''
erro = 'Opção inválida.'

#Funções
def soma(x,y):
    resultado = x + y
    return resultado

def subtracao(x,y):
    resultado = x - y
    return resultado

def multiplicacao(x,y):
    resultado = x * y
    return resultado

def exponenciacao(x,y):
    resultado = x ** y
    return resultado

def divisao(x,y):
    resultado = x // y
    return resultado


#Início do programa
print(boas_vindas)
print(opcoes)

while True:
    opcao_escolhida = int(input(''))
    if opcao_escolhida < 1 or opcao_escolhida > 9:
        print(erro)
        print(opcoes)
    elif opcao_escolhida == 9:
        print(finalizacao)
        break
    else:
        valor_1 = int(input('Informe o primeiro valor: '))
        valor_2 = int(input('Informe o segundo valor: '))
        if opcao_escolhida == 1:
            print('O total da soma é', soma(valor_1, valor_2))
            print(interacao)
            resposta_interacao = int(input(''))
            if resposta_interacao == 1:
                print(opcoes)
            elif resposta_interacao < 1 or resposta_interacao > 2:
                print(erro)
                print(interacao)
            else:
                break
        elif opcao_escolhida == 2:
            print('O resultado da subtração é', subtracao(valor_1, valor_2))
            print(interacao)
            resposta_interacao = int(input(''))
            if resposta_interacao == 1:
                print(opcoes)
            elif resposta_interacao < 1 or resposta_interacao > 2:
                print(erro)
                print(interacao)
            else:
                break
        elif opcao_escolhida == 3:
            print('O resultado da multiplicação é', multiplicacao(valor_1, valor_2))
            print(interacao)
            resposta_interacao = int(input(''))
            if resposta_interacao == 1:
                print(opcoes)
            elif resposta_interacao < 1 or resposta_interacao > 2:
                print(erro)
                print(interacao)
            else:
                break
        elif opcao_escolhida == 4:
            print('O resultado da exponenciação é', exponenciacao(valor_1, valor_2))
            print(interacao)
            resposta_interacao = int(input(''))
            if resposta_interacao == 1:
                print(opcoes)
            elif resposta_interacao < 1 or resposta_interacao > 2:
                print(erro)
                print(interacao)
            else:
                break
        elif opcao_escolhida == 5:
            print('O resultado da divisão é', divisao(valor_1, valor_2))
            print(interacao)
            resposta_interacao = int(input(''))
            if resposta_interacao == 1:
                print(opcoes)
            elif resposta_interacao < 1 or resposta_interacao > 2:
                print(erro)
                print(interacao)
            else:
                break
        elif opcao_escolhida == 6:
            primeiro_numero = valor_1 % 2
            segundo_numero = valor_2 % 2
            if primeiro_numero == 0 and segundo_numero == 0:
                print('Os dois números são pares!')
                print(interacao)
                resposta_interacao = int(input(''))
                if resposta_interacao == 1:
                    print(opcoes)
                elif resposta_interacao < 1 or resposta_interacao > 2:
                    print(erro)
                    print(interacao)
                else:
                    break
            elif primeiro_numero == 0 and segundo_numero != 0:
                print('O número', valor_1, 'é par! Já o', valor_2, 'é ímpar!')
                print(interacao)
                resposta_interacao = int(input(''))
                if resposta_interacao == 1:
                    print(opcoes)
                elif resposta_interacao < 1 or resposta_interacao > 2:
                    print(erro)
                    print(interacao)
                else:
                    break
            elif primeiro_numero != 0 and segundo_numero == 0:
                print('O número', valor_2, 'é par! Já o', valor_1, 'é ímpar!')
                print(interacao)
                resposta_interacao = int(input(''))
                if resposta_interacao == 1:
                    print(opcoes)
                elif resposta_interacao < 1 or resposta_interacao > 2:
                    print(erro)
                    print(interacao)
                else:
                    break
            else:
                print('Os dois números são ímpares!')
                print(interacao)
                resposta_interacao = int(input(''))
                if resposta_interacao == 1:
                    print(opcoes)
                elif resposta_interacao < 1 or resposta_interacao > 2:
                    print(erro)
                    print(interacao)
                else:
                    break
        elif opcao_escolhida == 7:
            if valor_1 > valor_2:
                print('O número', valor_1, 'é maior que o', valor_2)
                print(interacao)
                resposta_interacao = int(input(''))
                if resposta_interacao == 1:
                    print(opcoes)
                elif resposta_interacao < 1 or resposta_interacao > 2:
                    print(erro)
                    print(interacao)
                else:
                    break
            elif valor_1 == valor_2:
                print('Os números são iguais!')
                print(interacao)
                resposta_interacao = int(input(''))
                if resposta_interacao == 1:
                    print(opcoes)
                elif resposta_interacao < 1 or resposta_interacao > 2:
                    print(erro)
                    print(interacao)
                else:
                    break
            else:
                print('O número', valor_2, 'é maior que o', valor_1)
                print(interacao)
                resposta_interacao = int(input(''))
                if resposta_interacao == 1:
                    print(opcoes)
                elif resposta_interacao < 1 or resposta_interacao > 2:
                    print(erro)
                    print(interacao)
                else:
                    break
        elif opcao_escolhida == 8:
            print('O total da soma é', soma(valor_1, valor_2))
            print('O resultado da subtração é', subtracao(valor_1, valor_2))
            print('O resultado da multiplicação é', multiplicacao(valor_1, valor_2))
            print('O resultado da exponenciação é', exponenciacao(valor_1, valor_2))
            print('O resultado da divisão é', divisao(valor_1, valor_2))

            primeiro_numero = valor_1 % 2
            segundo_numero = valor_2 % 2
            if primeiro_numero == 0 and segundo_numero == 0:
                print('Os dois números são pares!')
            elif primeiro_numero == 0 and segundo_numero != 0:
                print('O número', valor_1, 'é par! Já o', valor_2, 'é ímpar!')
            elif primeiro_numero != 0 and segundo_numero == 0:
                print('O número', valor_2, 'é par! Já o', valor_1, 'é ímpar!')

            if valor_1 > valor_2:
                print('O número', valor_1, 'é maior que o', valor_2)
            elif valor_1 == valor_2:
                print('Os números são iguais!')
            else:
                print('O número', valor_2, 'é maior que o', valor_1)

            print(interacao)
            resposta_interacao = int(input(''))
            if resposta_interacao == 1:
                print(opcoes)
            elif resposta_interacao < 1 or resposta_interacao > 2:
                print(erro)
                print(interacao)
            else:
                break

